/**
 * OneDelivery — Package Definitions (mobile)
 * Keep in sync with backend/src/config/packages.js
 */
export const SELLER_PACKAGES = [
  {
    id: "seller_free",
    name: "Free Seller",
    price: 0,
    free_deliveries: 0,
    max_products: 10,
    popup_ads: false,
    in_app_ads: false,
    verified_badge: false,
    recommendations: 0,
    is_free: true,
    badge: null as string | null,
    color: "#64748B",
    description: "Get started — list products and reach buyers across Tanzania.",
    features: [
      "List up to 10 products",
      "Basic product listing",
      "Chat with customers",
      "Order management",
    ],
  },
  {
    id: "seller_basic",
    name: "Basic Seller",
    price: 80000,
    free_deliveries: 15,
    max_products: 50,
    popup_ads: true,
    in_app_ads: false,
    verified_badge: false,
    recommendations: 5,
    is_free: false,
    badge: "🔵 Basic",
    color: "#3B82F6",
    description: "Grow your business with delivery perks and greater visibility.",
    features: [
      "List up to 50 products",
      "15 free deliveries per month",
      "Pop-up on customer screen",
      "5 product recommendations",
      "Priority customer chat",
      "24h product approval",
    ],
  },
  {
    id: "seller_premium",
    name: "Premium Seller",
    price: 150000,
    free_deliveries: 30,
    max_products: 200,
    popup_ads: true,
    in_app_ads: true,
    verified_badge: false,
    recommendations: 20,
    is_free: false,
    badge: "⭐ Premium",
    color: "#F97316",
    description: "Maximize reach with ads, 30 free deliveries and premium placement.",
    features: [
      "List up to 200 products",
      "30 free deliveries per month",
      "Pop-up ads (frequent)",
      "In-app banner ads",
      "20 product recommendations",
      "Featured product placement",
      "Advanced analytics",
    ],
  },
  {
    id: "seller_elite",
    name: "Elite Premium",
    price: 300000,
    free_deliveries: 60,
    max_products: 0, // unlimited
    popup_ads: true,
    in_app_ads: true,
    verified_badge: true,
    recommendations: 999,
    is_free: false,
    badge: "👑 Elite",
    color: "#F59E0B",
    description: "Unlimited products, verified badge, maximum exposure.",
    features: [
      "Unlimited product listings",
      "60 free deliveries per month",
      "Maximum pop-up frequency",
      "Premium in-app ads",
      "Always recommended to buyers",
      "✅ Verified Seller Badge",
      "Top search ranking",
      "Instant product approval",
      "Dedicated account manager",
    ],
  },
];

export const CUSTOMER_PACKAGES = [
  { id: "customer_free",    name: "Standard",         price: 0,     is_free: true,  badge: null,        color: "#64748B", features: ["Browse & buy products", "Standard delivery", "Order tracking"] },
  { id: "customer_premium", name: "Premium Customer", price: 5000,  is_free: false, badge: "⭐ Premium", color: "#F97316", features: ["Free shipping over TZS 20,000", "Priority delivery", "Exclusive deals"] },
  { id: "customer_vip",     name: "VIP Customer",     price: 10000, is_free: false, badge: "👑 VIP",     color: "#F59E0B", features: ["Free shipping ALL orders", "5% cashback", "VIP flash sales", "Dedicated manager"] },
];
